function WriteS0MapAsDicom(image, instanceNumber, seriesUid, seriesNumber, ...
    seriesDescription, headerTemplate, fileName, imageMask)
    % MSU T1 Map Tool plug-in for ClearCanvas ImageViewer
    % Copyright (C) 2011-2013, Michigan State University
    % Author:  Matt Latourette
    %
    % This software modifies the ClearCanvas RIS/PACS open source project.
    %
    % This program is free software: you can redistribute it and/or modify
    % it under the terms of the GNU General Public License as published by
    % the Free Software Foundation, either version 3 of the License, or
    % (at your option) any later version.
    %
    % This program is distributed in the hope that it will be useful,
    % but WITHOUT ANY WARRANTY; without even the implied warranty of
    % MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    % GNU General Public License for more details.
    %
    % You should have received a copy of the GNU General Public License
    % along with this program.  If not, see <http://www.gnu.org/licenses/>.
    %
    %
    % Filename:  WriteT1AsDicom.m
    % Created:  2011
    % Description:  Writes the specified image as a DICOM file, including
    % attributes that are appropriate for a T1 map, and taking any 
    % attributes that are to remain unchanged from the source images from 
    % the supplied header template.  The series instance UID and the 
    % series number to be used for the new image are specified by the 
    % caller.
    %
    % Usage:
    % WriteT1AsDicom(image, instanceNumber, seriesUid, seriesNumber, ...
    %   seriesDescription, headerTemplate, fileName)
    datetime = now();
    header = struct('SpecificCharacterSet', headerTemplate.SpecificCharacterSet, ...
        'ImageType', 'DERIVED\SECONDARY\OTHER', ...
        'SOPInstanceUID', dicomuid(), ...
        'StudyDate', headerTemplate.StudyDate, ...
        'ContentDate', datestr(datetime, 'yyyymmdd'), ...
        'StudyTime', headerTemplate.StudyTime, ...
        'ContentTime', datestr(datetime, 'HHMMSS'), ...
        'AccessionNumber', headerTemplate.AccessionNumber, ...
        'Modality', 'MR', ...
        'Manufacturer', 'MSU Radiology Research', ...
        'ManufacturerModelName', 'T1 Mapper', ...
        'SoftwareVersion', 'MSU ClearCanvas T1 plug-in alpha-1.0.00', ...
        'ReferringPhysicianName', headerTemplate.ReferringPhysicianName, ...
        'PatientName', headerTemplate.PatientName, ...
        'PatientID', headerTemplate.PatientID, ...
        'PatientBirthDate', headerTemplate.PatientBirthDate, ...
        'PatientSex', headerTemplate.PatientSex, ...
        'ScanningSequence', headerTemplate.ScanningSequence, ...
        'SequenceVariant', headerTemplate.SequenceVariant, ...
        'ScanOptions', headerTemplate.ScanOptions, ...
        'MRAcquisitionType', headerTemplate.MRAcquisitionType, ...
        'SliceThickness', headerTemplate.SliceThickness, ...
        'RepetitionTime', headerTemplate.RepetitionTime, ...
        'EchoTime', headerTemplate.EchoTime, ...
        'EchoTrainLength', 1, ...
        'PatientPosition', headerTemplate.PatientPosition, ...
        'StudyInstanceUID', headerTemplate.StudyInstanceUID, ...
        'SeriesInstanceUID', seriesUid, ...
        'StudyID', headerTemplate.StudyID, ...
        'SeriesNumber', seriesNumber, ...
        'SeriesDescription', seriesDescription, ...
        'InstanceNumber', instanceNumber, ...
        'ImagePositionPatient', headerTemplate.ImagePositionPatient, ...
        'ImageOrientationPatient', headerTemplate.ImageOrientationPatient, ...
        'FrameOfReferenceUID', headerTemplate.FrameOfReferenceUID, ...
        'PositionReferenceIndicator', headerTemplate.PositionReferenceIndicator, ...
        'SamplesPerPixel', headerTemplate.SamplesPerPixel, ...
        'PhotometricInterpretation', headerTemplate.PhotometricInterpretation, ...
        'Rows', headerTemplate.Rows, ...
        'Columns', headerTemplate.Columns, ...
        'PixelSpacing', headerTemplate.PixelSpacing, ...
        'BitsAllocated', headerTemplate.BitsAllocated, ...
        'BitsStored', headerTemplate.BitsStored, ...
        'HighBit', headerTemplate.HighBit, ...
        'PixelRepresentation', 0, ...
        'SmallestImagePixelValue', uint16(min(double(reshape(image, 1, [])))), ...
        'LargestImagePixelValue', uint16(max(double(reshape(image, 1, [])))), ...
        'WindowCenter', uint16(mean(double(reshape(imageMask, 1, [])))), ...
        'WindowWidth', uint16(2*std(double(reshape(imageMask, 1, [])))));
    
    sourceFields = fieldnames(headerTemplate);
    
    for j = 1:length(sourceFields)
        currentField = sourceFields{j};
        switch currentField
            case {'Laterality', 'SliceLocation', 'StudyDescription', ...
                    'AcquisitionDate', 'AcquisitionTime', 'InstitutionName', ...
                    'PhysicianReadingStudy', 'OperatorName', 'PatientAge', ...
                    'PatientWeight', 'AdditionalPatientHistory', ...
                    'ImagingFrequency', 'ImagedNucleus', 'MagneticFieldStrength', ...
                    'SpacingBetweenSlices', 'PercentSampling', 'PercentPhaseFieldOfView', ...
                    'ReconstructionDiameter', 'ReceiveCoilName', 'TransmitCoilName', ...
                    'AcquisitionMatrix', 'InPlanePhaseEncodingDirection', ...
                    'InversionTime', 'TemporalPositionIdentifier', ...
                    'NumberOfTemporalPositions', 'TemporalResolution', ...
                    'ContrastBolusAgent'}
                header.(currentField) = headerTemplate.(currentField);
            case 'SeriesDate'
                header.(currentField) = header.ContentDate;
            case 'SeriesTime'
                header.(currentField) = header.ContentTime;
            otherwise
                % do nothing
        end
    end

    dicomwrite(uint16(image), fileName, 'ObjectType', 'MR Image Storage', ...
        'WritePrivate', true, header);
end

